# -*- coding: utf-8 -*-
"""Cv-Co1-AT1-Q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KzyP0Wl3nBDmWoO2RPOIZHlerag66qNe
"""

import cv2
import matplotlib.pyplot as plt
import urllib.request
import numpy as np

# Download a sample image
url = "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/lena.jpg"
urllib.request.urlretrieve(url, "sample.jpg")

# Read image
image = cv2.imread("sample.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Downsample (Improper Sampling)
sampled = image[::4, ::4]

# Upsample (Blurred)
blurred = cv2.resize(sampled, (image.shape[1], image.shape[0]),
                     interpolation=cv2.INTER_LINEAR)

# Sharpen
kernel = np.array([[0,-1,0],
                   [-1,5,-1],
                   [0,-1,0]])

corrected = cv2.filter2D(blurred, -1, kernel)

# Display
plt.figure(figsize=(15,5))

plt.subplot(131)
plt.imshow(image)
plt.title("Original")
plt.axis("off")

plt.subplot(132)
plt.imshow(blurred)
plt.title("Blurred")
plt.axis("off")

plt.subplot(133)
plt.imshow(corrected)
plt.title("Corrected")
plt.axis("off")

plt.show()
